### ISSUE TITLE
How to load image from a remote url

### ISSUE THREAD

**Issue by PKDmeDEV** [hannesa2/panoramaGL#280]
Hi,
As I understand, it takes images from raw folder. I want to load images from a url. Has anyone tried it ?

Thanks

**Comment by hannesa2** [comment]
You mean this ?

```
        val plHotspot1 = ActionPLHotspot(
            this,
            hotSpotId,
            PLImage(BitmapFactory.decodeResource(resources, R.raw.hotspot)),
            0f,
            0f,
            PLConstants.kDefaultHotspotSize,
            PLConstants.kDefaultHotspotSize
        )
```

It needs a bitmap and [here](https://www.google.com/search?q=android+bitmap+url) you find it

**Comment by PKDmeDEV** [comment]
Not just the hotspot, but the panorama itself. I found in old issues there was some comment of loading it from cache.

**Comment by hannesa2** [comment]
Then show me the comment.
Btw, when you show me what you want to do **exactly**, I need no guessing, what you want to do.

**Comment by PKDmeDEV** [comment]
I mentioned clearly in the topic, loading images from remote url, I didn't
left you to the guess anything. One of the closed issue has the similar
query, and their they mentioned to work with cache.

**Comment by hannesa2** [comment]
I don't search the code for you. If you needs help, you have to point me to the right place

**Comment by PKDmeDEV** [comment]
Nevermind, got it working what I was trying to do. I understand that you are not creator of this library so not well versed with its nuances.
