### ISSUE TITLE
error java.lang.NullPointerException

### ISSUE THREAD

**Issue by mmrvega** [hannesa2/panoramaGL#283]
```
 public void vr() {
        setContentView(R.layout.fragment_vr);
        PLManager plManager = new PLManager(MainActivity.this);
        plManager.setContentView(R.layout.fragment_vr);
        PLSphericalPanorama panorama = new PLSphericalPanorama();
        panorama.getCamera().lookAt(30.0f, 90.0f);

        panorama.setImage(new PLImage(PLUtils.getBitmap(MainActivity.this, R.raw.room_vr), false));
        plManager.setPanorama(panorama);
    }
```

when i try to load the R.layout.fragment_vr it says 
Required type:
ViewGroup
Provided:
int

then tried this 
```
 LayoutInflater inflater = LayoutInflater.from(MainActivity.this);
        ViewGroup contentView = (ViewGroup) inflater.inflate(R.layout.fragment_vr, null);
        plManager.setContentView(contentView);
```

and i get this error                                                       
java.lang.NullPointerException
                                                                                                    	at com.panoramagl.PLManager.onGLSurfaceViewCreated(PLManager.kt:1393)

**Comment by hannesa2** [comment]
For me it looks like `mInternalTouches` is not initialized.
The code is not very smart made, but I guess you need somewhere a `PLManager.onCreate()`

Please see in running sample, how it's done there https://github.com/hannesa2/panoramaGL/blob/d9e8c4dde01888b35a9467d7a80611fb19755774/app/src/main/java/com/panoramagl/sample/MainActivity.kt#L31-L33
