### ISSUE TITLE
stop continuous scrolling

### ISSUE THREAD

**Issue by dekemega** [hannesa2/panoramagl#8]
I am using android panoramaGL,it is working fine 360 sphere and sensor rotation. But when you click on image and scroll some distance with out lifting fingure on screen, it is scrolling continuously(my fingure is not moving but it is scrolling)how to stop it...

**Comment by PhilippeTroller** [comment]
same problem.

**Comment by nachtien** [comment]
@hannesa2 Is there a solution to stopping it from scrolling continuously?

**Comment by grammesm** [comment]
Looking at various panorama libraries and this one seems the easiest to use for cubic projection, but agree with others - trying to navigate with your finger is very confusing.. seems like a speed vector for movement based on the distance from your first tap, rather than just moving with the finger.

**Comment by grammesm** [comment]
FWIW I was able to fix this in my local copy.

in `PLManager.kt`

Update `touchesMoved`

```kotlin
    fun touchesMoved(touches: List<UITouch?>?, event: MotionEvent?) {
        val listenerExists = mListener != null
        if (listenerExists) mListener!!.onTouchesMoved(this, touches, event)
        if (this.isLocked || isValidForCameraAnimation || mIsValidForTransition || !isTouchInView(touches) || listenerExists && !mListener!!.onShouldMoveTouching(
                this,
                touches,
                event
            )
        ) return
        mTouchStatus = PLTouchStatus.PLTouchStatusMoved
        mStartPoint!!.setValues(mEndPoint) // <------- **** NEW LINE ****
        if (!executeDefaultAction(touches, PLTouchEventType.PLTouchEventTypeMoved)) mEndPoint!!.setValues(getLocationOfFirstTouch(touches))
        if (listenerExists) mListener!!.onDidMoveTouching(this, touches, event)
    }
```

And then in the `MainActivity.kt` file setting the rotational sensitivity to max before setting the panorama
```kotlin
        panorama.camera.rotationSensitivity = 180f
```

Could put the first change behind some configuration of PLManager?

May want to up the max allowable sensitivity a bit, to give a little more than 1:1 sensitivity when moving the map around..

**Comment by hannesa2** [comment]
Nice, do you want to share your solution to the community with a pull request ?

**Comment by grammesm** [comment]
@hannesa2  Let me tidy it up and I'll submit something

**Comment by hannesa2** [comment]
I tried to reproduce the miss function. 
First, I use current master and I observed no miss function.

Second, I switched on acceleration
`isAccelerometerEnabled = true`
and I observed no miss function.

Please tell me, what I've to do, to see it
