### ISSUE TITLE
OutOfMemoryError 

### ISSUE THREAD

**Issue by ViktorYellows** [hannesa2/panoramagl#88]
Thanks for creating this library, when I set panorama image many times by clicking previous/next buttons i got OutOfMemoryError. 

Also i tried in Your sample project https://github.com/hannesa2/panoramagl/blob/master/app/src/main/java/com/panoramagl/sample/MainActivity.kt i got the same OutOfMemoryError. 

My code:
`val panorama = PLSphericalPanorama()`
`val plImage = PLImage(bm, false)`
`panorama.setImage(plImage)`
` plManager.panorama = panorama`

After debugging i found that error is not happening when 
`plManager.panorama = panorama`
 is commented, so think that the problem is in that line

**Comment by hannesa2** [comment]
A: please can you make a pull request where I can easy reproduce the error ?
B: I made some Kotlin conversion https://github.com/hannesa2/panoramagl/releases/tag/1.7. Does the error still exists ?

**Comment by ViktorYellows** [comment]
I create new repository with sample, when You can reproduce an error. The error still exists in 1.7 version.
https://github.com/ViktorYellows/testPanoramaGl

By changing panoramas many times You  can catch OOM error, i add README file

**Comment by hannesa2** [comment]
Currently it's not reproduce-able https://github.com/ViktorYellows/testPanoramaGl/pull/3, I close it.
but when you have a real evidence please reopen it again
